#!/usr/bin/env node
// Reads each per-template <Tag>.html / <Tag>.style.css under src/library/templates/<Tag>/ and emits a
// deterministic src/generated/templates.gen.ts. Keys are written in MANIFEST order so the output
// is stable byte-for-byte across runs (no timestamps, no Date.now, no randomness).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const stockDir = join(__dirname, '..', 'src', 'library');
const templatesDir = join(stockDir, 'templates');
const baseCssFile = join(stockDir, 'base.style.css');
const outDir = join(stockDir, 'generated');
const outFile = join(outDir, 'templates.gen.ts');

/** Emission order for the shell (manifest order = cascade + template-definition order). Must match MANIFEST in src/library/index.ts. */
const MANIFEST = [
  'Shape',
  'Icon',
  'Activity',
  'Event',
  'Gateway',
  'Textbox',
  'Group',
  'Lane',
  'Pool',
  'Divider',
  'DatabaseTable',
  'Legend',
  'Relationship',
  'DatabaseRelationship',
  'Badge',
];

// Source files are authored PRETTY (indented, multi-line) for editing; the codegen minifies them to
// the compact form the shell emits, so the emitted output stays byte-identical regardless of source
// formatting. Templates keep text tight to its element, so only whitespace BETWEEN tags is structural.

/** Collapse whitespace-only runs between tags; trim. Text content (never whitespace-only) is kept. */
function minifyHtml(html) {
  return html.replace(/>\s+</g, '><').trim();
}

/** Compact CSS to the shell form: no whitespace around punctuation, no trailing `;`, single spaces. */
function minifyCss(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\s+/g, ' ')
    .replace(/\s*([{}:;,])\s*/g, '$1')
    .replace(/;}/g, '}')
    .trim();
}

const htmlEntries = [];
const cssEntries = [];

for (const tag of MANIFEST) {
  const html = minifyHtml(
    readFileSync(join(templatesDir, tag, `${tag}.html`), 'utf8'),
  );
  const css = minifyCss(
    readFileSync(join(templatesDir, tag, `${tag}.style.css`), 'utf8'),
  );
  htmlEntries.push(`  ${JSON.stringify(tag)}: ${JSON.stringify(html)},`);
  cssEntries.push(`  ${JSON.stringify(tag)}: ${JSON.stringify(css)},`);
}

const baseCss = minifyCss(readFileSync(baseCssFile, 'utf8'));

const banner =
  '// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.\n// Source of truth: src/library/base.style.css and src/library/templates/<Tag>/<Tag>.{html,style.css}.\n';

const output =
  banner +
  '\n' +
  `export const BASE_CSS = ${JSON.stringify(baseCss)};\n` +
  '\n' +
  'export const TEMPLATE_HTML: Record<string, string> = {\n' +
  htmlEntries.join('\n') +
  '\n};\n' +
  '\n' +
  'export const TEMPLATE_CSS: Record<string, string> = {\n' +
  cssEntries.join('\n') +
  '\n};\n';

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, output, 'utf8');
